name: iOS Release
on: workflow_dispatch
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/ios/iphoneos
